require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.3

  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
