require:
  - rubocop-rails

inherit_gem:
  rubocop-discourse: default.yml

AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable

  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'vendor/**/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

StringLiterals:
  Enabled: false
